AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  Web Hook for Source Version Control tag pushes
Parameters:
  CodeDeliveryNameParameter:
    Type: String
    Default: my-cd
    AllowedPattern: '^[a-z][a-z0-9-]*$'
    ConstraintDescription: 'Must be only include lowercase letters and - and must start with a letter'
    MinLength: 4
    MaxLength: 20
    Description: The name for the Continuous Delivery resources
  ProjectNameParameter:
    Type: String
    AllowedPattern: '^[a-z][a-z0-9-]*$'
    ConstraintDescription: 'Must be only include lowercase letters and - and must start with a letter'
    MinLength: 4
    MaxLength: 20
    Description: The name for the project
  ServiceNameParameter:
    Type: String
    AllowedPattern: '^[a-z][a-z0-9-]*$'
    ConstraintDescription: 'Must be only include lowercase letters and - and must start with a letter'
    MinLength: 4
    MaxLength: 20
    Description: The name for the service
  EnvironmentParameter:
    Type: String
    Default: test
    AllowedValues:
      - dev
      - test
      - prod
    Description: Enter dev, test or prod. Default is test
Resources:
  PreRelease:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-PreRelease'
      Handler: src/api/handler.prerelease
      Runtime: nodejs6.10
      Role: !GetAtt LambdaRole.Arn
      CodeUri: .
      Description: >-
        Pre-release a Lambda function by creating a new versioning and shifting the green alias to it
      MemorySize: 128
      Timeout: 10
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: CodeBuildPermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - "arn:aws:logs:*:*:*"
            - Effect: "Allow"
              Action:
                - codepipeline:PutJobSuccessResult
                - codepipeline:putJobFailureResult
              Resource:
                - "*"
            # To Do, remove ListFunctions permission
            - Effect: "Allow"
              Action:
                - lambda:ListFunctions
              Resource:
                - "*"
            - Effect: Allow
              Action:
                - cloudformation:ListStackResources
              Resource:
                - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/*"
  Pipeline:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        CodeDeliveryNameParameter: !Ref CodeDeliveryNameParameter
        ProjectNameParameter: !Ref ProjectNameParameter
        ServiceNameParameter: !Ref ServiceNameParameter
        EnvironmentParameter: !Ref EnvironmentParameter
      TemplateURL: ./common/pipelines/SAM-blue-green-with-IAM.cf.yml
      TimeoutInMinutes: 2
