AWSTemplateFormatVersion: '2010-09-09'
Description: Web Hook for Source Version Control tag pushes
Parameters:
  EnvironmentParameter:
    AllowedValues:
    - dev
    - test
    - prod
    Default: test
    Description: Enter dev, test or prod. Default is test.
    Type: String
  ProjectNameParameter:
    AllowedPattern: ^[a-z][a-z0-9-]*$
    ConstraintDescription: Must be only include lowercase letters and - and must start
      with a letter
    Description: The name for the project
    MaxLength: 20
    MinLength: 4
    Type: String
Resources:
  Hook:
    Properties:
      CodeUri: s3://h4-tmp/package/my-cd/svc-vcs-hook/1.0.0/dev/e82fab95dceed25dd5041185c72fe3b7
      Description: Web Hook function for GitHub tag pushes
      Environment:
        Variables:
          CODE_BUILD_PROJECT:
            Fn::Sub: ${ProjectNameParameter}-${EnvironmentParameter}-extract
      Events:
        Hook:
          Properties:
            Method: post
            Path: /hook
          Type: Api
      FunctionName:
        Fn::Sub: ${AWS::StackName}-Hook
      Handler: src/index.hook
      MemorySize: 128
      Role:
        Fn::ImportValue:
          Fn::Sub: ${ProjectNameParameter}-${EnvironmentParameter}-LambdaCodeBuildRoleArn
      Runtime: nodejs6.10
      Timeout: 10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
