AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  Web Hook for Source Version Control tag pushes
Parameters:
  ProjectNameParameter:
    Type: String
    AllowedPattern: '^[a-z][a-z0-9-]*$'
    ConstraintDescription: 'Must be only include lowercase letters and - and must start with a letter'
    MinLength: 4
    MaxLength: 20
    Description: The name for the project
  EnvironmentParameter:
    Type: String
    Default: test
    AllowedValues:
      - dev
      - test
      - prod
    Description: Enter dev, test or prod. Default is test.
Resources:
  Hook:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub '${AWS::StackName}-Hook'
      Handler: src/index.hook
      Runtime: nodejs6.10
      # 01/06/2017 - Polices do not currently get added to the default function
      # role with SAM, so a role needs to be used instead i.e. this doesn't work
      # Policies:
      #   - Fn::ImportValue:
      #       !Sub '${ProjectNameParameter}-${EnvironmentParameter}-LambdaBasicExecutionPolicy'
      #   - Fn::ImportValue:
      #       !Sub '${ProjectNameParameter}-${EnvironmentParameter}-LambdaCodeBuildPolicy'
      Role:
        Fn::ImportValue:
          !Sub '${ProjectNameParameter}-${EnvironmentParameter}-LambdaCodeBuildRoleArn'
      Environment:
        Variables:
          CODE_BUILD_PROJECT: !Sub '${ProjectNameParameter}-${EnvironmentParameter}-extract'
      CodeUri: .
      Description: >-
        Web Hook function for GitHub tag pushes
      MemorySize: 128
      Timeout: 10
      Events:
        Hook:
          Type: Api
          Properties:
            Path: /hook
            Method: post
